import 'bootstrap/dist/css/bootstrap.min.css';
import { Geist, Geist_Mono } from "next/font/google";
import BootstrapProvider from "./bootstrap-provider";
import Header from "./components/Header/Header";
import "./globals.css";
import Landing from "./components/Landing/Landing.js";
import ContextProvider from './components/Context-Api/Context-Api';
import Footer from './components/Footer/Footer';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider>
        <Header/>
        <BootstrapProvider />
        <div className='mt-[70px]'>
        {children}
        </div>
        <Footer/>
        </ContextProvider>
      </body>
    </html>
  );
}
